import type { MneloRepository } from './repository';
import { RepositoryError } from './repository';
export function unavailableRepository(): MneloRepository {
  const fail = async (): Promise<never> => {
    throw new RepositoryError('UNAVAILABLE');
  };
  return {
    mode: 'unavailable',
    restoreSession: async () => null,
    watchSession: () => () => undefined,
    requestOtp: fail,
    verifyOtp: fail,
    logout: fail,
    saveProfile: fail,
    profile: fail,
    updateProfilePreferences: fail,
    uploadAvatar: fail,
    avatarUrl: fail,
    searchProfiles: fail,
    conversation: fail,
    conversations: fail,
    messages: fail,
    sendMessage: fail,
    forwardMessage: fail,
    uploadAttachment: fail,
    sendAttachment: fail,
    attachment: fail,
    sendLocation: fail,
    sendContact: fail,
    react: fail,
    deleteMessage: fail,
    markRead: fail,
    createGroup: fail,
    group: fail,
    renameGroup: fail,
    addGroupMember: fail,
    manageGroupMember: fail,
    leaveGroup: fail,
    setGroupAvatar: fail,
    interpret: fail,
    clarify: fail,
    need: fail,
    saveNeed: fail,
    matches: fail,
    profileIntents: fail,
    needs: fail,
    setNeedStatus: fail,
    requestConnection: fail,
    relationship: fail,
    openDirectConversation: fail,
    requests: fail,
    respondRequest: fail,
    connections: fail,
    connectionDetails: fail,
    completedConnections: fail,
    confirmCompletion: fail,
    submitReview: fail,
    reviews: fail,
    verifications: fail,
    revealPhone: fail,
    privacy: fail,
    updatePrivacy: fail,
    startCall: fail,
    call: fail,
    respondCall: fail,
    callToken: fail,
    incomingCall: async () => null,
    subscribeCalls: () => () => undefined,
    notificationPreferences: fail,
    updateNotificationPreferences: fail,
    registerDevice: fail,
    registerPush: fail,
    disablePush: fail,
    resolveNotification: fail,
    devices: fail,
    revokeOtherDevices: fail,
    validateSession: fail,
    forgetSession: fail,
    currentDeviceId: fail,
    block: fail,
    unblock: fail,
    blockedProfiles: fail,
    report: fail,
    requestAccountDeletion: fail,
    pendingAccountDeletion: async () => false,
    accountDeletionStatus: fail,
    clearAccountDeletionReceipt: fail,
    subscribeInbox: () => () => undefined,
    subscribe: () => () => undefined,
  };
}
