export const composeEn = {
  close: 'Close',
  clearSearch: 'Clear search',
  newChat: 'New chat',
  newContact: 'New contact',
  search: 'Search name or number',
  contacts: 'Contacts on Mnelo',
  noContacts: 'Your saved Mnelo contacts will appear here.',
  noResults: 'No contacts found.',
  chatNumber: 'Chat with {{number}}',
  callNumber: 'Call {{number}}',
  keypad: 'Keypad',
  addByCode: 'Add with Mnelo code',
  invite: 'Invite to Mnelo',
  invitation: 'Join me on Mnelo: https://mnelo.com',
  voice: 'Voice call {{name}}',
  video: 'Video call {{name}}',
  deleteDigit: 'Delete digit',
  clearNumber: 'Clear number',
  plus: 'Add country code prefix',
} as const;
export const composeKa: Record<keyof typeof composeEn, string> = {
  close: 'დახურვა',
  clearSearch: 'ძებნის გასუფთავება',
  newChat: 'ახალი ჩატი',
  newContact: 'ახალი კონტაქტი',
  search: 'სახელის ან ნომრის ძებნა',
  contacts: 'კონტაქტები Mnelo-ში',
  noContacts: 'აქ გამოჩნდება შენახული Mnelo კონტაქტები.',
  noResults: 'კონტაქტები ვერ მოიძებნა.',
  chatNumber: 'მიმოწერა: {{number}}',
  callNumber: 'დარეკვა: {{number}}',
  keypad: 'ნომრის აკრეფა',
  addByCode: 'Mnelo კოდით დამატება',
  invite: 'მოწვევა Mnelo-ში',
  invitation: 'შემომიერთდი Mnelo-ში: https://mnelo.com',
  voice: 'ხმოვანი ზარი: {{name}}',
  video: 'ვიდეოზარი: {{name}}',
  deleteDigit: 'ციფრის წაშლა',
  clearNumber: 'ნომრის გასუფთავება',
  plus: 'ქვეყნის კოდის პრეფიქსის დამატება',
};
