export const cardEn = {
  title: 'My card',
  info: 'Contact info',
  blockHint: 'You won’t receive messages or calls from this contact. You can unblock them here.',
  historyCleared: 'History cleared from this device.',
  identityDetails: 'Profile details',
  view: 'Contact card',
  edit: 'Edit profile',
  scan: 'Scan QR code',
  share: 'Share my card',
  qr: 'My QR code',
  photo: 'Profile photo',
  addPhoto: 'Add photo',
  changePhoto: 'Change photo',
  removePhoto: 'Remove photo',
  photoError: 'Choose a smaller photo and try again.',
  invalidDetails: 'Check your username, name length, email and website. Websites must use HTTPS.',
  headline: 'What you do',
  headlinePlaceholder: 'Designer, maker, good listener…',
  about: 'About you',
  aboutPlaceholder: 'A little more about you.',
  email: 'Email',
  website: 'Website',
  optional: 'Your contact card',
  detailsHint:
    'Optional. These details and your photo are shared with contacts you have added, when you connect. They can keep their copy.',
  privateHint: 'Your card stays on devices. Your QR shares only your name and Mnelo identity.',
  qrHint: 'Let someone scan this to add you on Mnelo.',
  scanHint: 'Scan the QR code on the other person’s Mnelo card.',
  scanPrivacy: 'The camera is used only to read a Mnelo QR code. No photo is saved.',
  camera: 'Open camera',
  cameraDenied: 'Camera access is off. You can allow it in Settings or paste a contact link.',
  cameraFailed: 'The camera could not start. Try again or paste their contact link.',
  settings: 'Open Settings',
  paste: 'Paste contact link',
  invalidCode: 'This is not a valid Mnelo contact code.',
  scanAgain: 'Scan again',
  add: 'Add contact',
  added: 'Contact added',
  confirmed: 'I am scanning this person’s code or have compared it with them.',
  verify:
    'Check whose code this is before adding them. A QR code is not an identity verification badge.',
  key: 'Mnelo identity',
  samePerson: 'This is your own card.',
  noCard: 'Their card will appear after you both add each other and connect.',
  openWebsite: 'Open website',
  sendEmail: 'Write an email',
  message: 'Message',
  voice: 'Voice call',
  invitation: 'Add me on Mnelo: {{link}}',
  join: 'Join Mnelo to add {{name}}',
  joinHint: 'Verify your phone number first, then return here to add this contact.',
  register: 'Continue to Mnelo',
  saved: 'Saved on this phone',
  link: 'Contact link',
  copied: 'Link copied',
  copy: 'Copy link',
  done: 'Done',
} as const;
export const cardKa: Record<keyof typeof cardEn, string> = {
  title: 'ჩემი ბარათი',
  info: 'კონტაქტის ინფორმაცია',
  blockHint: 'ამ კონტაქტის შეტყობინებებსა და ზარებს აღარ მიიღებ. განბლოკვა აქვე შეგიძლია.',
  historyCleared: 'ისტორია ამ მოწყობილობიდან წაიშალა.',
  identityDetails: 'პროფილის ინფორმაცია',
  view: 'კონტაქტის ბარათი',
  edit: 'პროფილის შეცვლა',
  scan: 'QR-ის სკანირება',
  share: 'ბარათის გაზიარება',
  qr: 'ჩემი QR კოდი',
  photo: 'პროფილის ფოტო',
  addPhoto: 'ფოტოს დამატება',
  changePhoto: 'ფოტოს შეცვლა',
  removePhoto: 'ფოტოს წაშლა',
  photoError: 'აირჩიე უფრო პატარა ფოტო და სცადე თავიდან.',
  invalidDetails:
    'გადაამოწმე იუზერნეიმი, სახელის სიგრძე, ელფოსტა და ვებგვერდი. ბმული HTTPS-ს უნდა იყენებდეს.',
  headline: 'რას საქმიანობ',
  headlinePlaceholder: 'დიზაინერი, შემოქმედი, კარგი მსმენელი…',
  about: 'შენ შესახებ',
  aboutPlaceholder: 'ცოტა მეტი შენ შესახებ.',
  email: 'ელფოსტა',
  website: 'ვებსაიტი',
  optional: 'შენი საკონტაქტო ბარათი',
  detailsHint:
    'არასავალდებულო. ფოტო და ეს ინფორმაცია შენს დამატებულ კონტაქტებს დაკავშირებისას გადაეცემა. მათ საკუთარი ასლის შენახვა შეუძლიათ.',
  privateHint: 'ბარათი მოწყობილობებზე რჩება. QR მხოლოდ სახელსა და Mnelo იდენტობას აზიარებს.',
  qrHint: 'შენ დასამატებლად სხვამ ეს კოდი Mnelo-თი დაასკანეროს.',
  scanHint: 'დაასკანერე მეორე ადამიანის Mnelo ბარათის QR კოდი.',
  scanPrivacy: 'კამერა მხოლოდ Mnelo კოდის წასაკითხად გამოიყენება. ფოტო არ ინახება.',
  camera: 'კამერის გახსნა',
  cameraDenied: 'კამერის წვდომა გამორთულია. ჩართე პარამეტრებიდან ან ჩასვი კონტაქტის ბმული.',
  cameraFailed: 'კამერა ვერ ჩაირთო. სცადე ხელახლა ან ჩასვი კონტაქტის ბმული.',
  settings: 'პარამეტრების გახსნა',
  paste: 'კონტაქტის ბმულის ჩასმა',
  invalidCode: 'ეს Mnelo-ს სწორი საკონტაქტო კოდი არ არის.',
  scanAgain: 'თავიდან სკანირება',
  add: 'კონტაქტის დამატება',
  added: 'კონტაქტი დამატებულია',
  confirmed: 'ამ ადამიანის კოდს ვასკანერებ ან მასთან შევადარე.',
  verify: 'დამატებამდე გადაამოწმე, ვისი კოდია. QR კოდი ვინაობის დამადასტურებელი ნიშანი არ არის.',
  key: 'Mnelo იდენტობა',
  samePerson: 'ეს შენი ბარათია.',
  noCard: 'მისი ბარათი გამოჩნდება, როცა ერთმანეთს დაამატებთ და დაუკავშირდებით.',
  openWebsite: 'ვებსაიტის გახსნა',
  sendEmail: 'ელფოსტის მიწერა',
  message: 'მიწერა',
  voice: 'ხმოვანი ზარი',
  invitation: 'დამამატე Mnelo-ში: {{link}}',
  join: 'შემოუერთდი Mnelo-ს: {{name}}',
  joinHint: 'ჯერ დაადასტურე შენი ნომერი, შემდეგ დაბრუნდი კონტაქტის დასამატებლად.',
  register: 'გაგრძელება Mnelo-ში',
  saved: 'შენახულია ამ ტელეფონზე',
  link: 'კონტაქტის ბმული',
  copied: 'ბმული დაკოპირებულია',
  copy: 'ბმულის კოპირება',
  done: 'მზადაა',
};
