import { deliveryV2 } from './delivery-mode';

export const messengerEn = {
  callReply: 'Reply with a message',
  callQuickReplies: 'Quick call replies',
  callQuickRepliesHint:
    'Choose a reply to decline the call and send a message. You can edit these replies.',
  callQuickRepliesEditHint:
    'Make these replies your own. They are ready whenever you cannot take a call.',
  privacyMessages: 'Private conversations',
  settingsStorage: 'Data on this device',
  notificationDelivery: 'Message alerts',
  notificationPreviews: 'Names and previews',
  notificationOn: 'Notifications are on',
  notificationOff: 'Notifications are off',
  callQuickReplyLabel: 'Reply {{number}}',
  callReplyMeeting: "I'm in a meeting. I'll call you back.",
  callReplyLater: "I can't talk now. I'll call you later.",
  callReplySoon: "I'll call you back in a few minutes.",
  editReplies: 'Edit replies',
  viewOriginal: 'Go to original message',
  exportChat: 'Export chat',
  exportPreparing: 'Preparing export…',
  exportLocalHint: 'Save a copy of the messages and media available on this device.',

  sendPoll: 'Send poll',
  sendEvent: 'Send event',
  pollHint: 'Ask the chat and let everyone vote.',
  eventHint: 'Make a plan together. Share the details with this chat.',
  pollOptions: 'Answer options',
  pollPlaceholder: 'What would you like to ask?',
  eventPlaceholder: 'Give your event a name',
  multipleAnswersHint: 'People can choose more than one option.',
  eventLocationPlaceholder: 'Add a place or meeting link',
  eventNotesPlaceholder: 'Anything else people should know?',
  poll: 'Poll',
  openChatSearch: 'Show chat search',
  attachmentContact: 'Contact',
  contactPhoneUnavailable: 'This contact has no phone number available to share.',
  exportTooLarge: 'This chat is too large to export as one ZIP file.',
  exportUnavailable: 'Chat export is unavailable on this device.',
  exportChanged: 'The chat changed during export. Please try again.',
  attachmentLocation: 'Location',
  attachmentMyLocation: 'My location',
  sendLocation: 'Send location',
  locationSearch: 'Search for a place or address',
  locationMap: 'Choose a place on the map',
  locationHint: 'Search for a place, or hold the map to drop a pin.',
  locationSelected: 'Selected location',
  locationSearching: 'Searching…',
  locationNoResults: 'No places found. Try another search or drop a pin.',
  locationChoose: 'Choose a place from the results.',
  locationCoordinatesHint:
    'Enter the coordinates of the place you want to share. You can preview it in Maps before sending.',
  latitude: 'Latitude',
  longitude: 'Longitude',
  event: 'Event',
  createPoll: 'Create poll',
  createEvent: 'Create event',
  pollQuestion: 'Question',
  pollOption: 'Option {{number}}',
  removeOption: 'Remove option {{number}}',
  addOption: 'Add option',
  multipleAnswers: 'Allow multiple answers',
  chooseMany: 'Choose one or more answers',
  chooseOne: 'Choose one answer',
  pollChoice: '{{option}}: {{count}} votes',
  pollVoters_one: '{{count}} participant voted',
  pollVoters_other: '{{count}} participants voted',
  eventTitle: 'Event name',
  eventStart: 'Starts',
  eventEnd: 'Ends',
  eventLocation: 'Location (optional)',
  eventNotes: 'Description (optional)',
  eventCalendarHint: 'People in this chat can add the event to their calendar.',
  addToCalendar: 'Add to calendar',
  phoneCalendar: 'Phone calendar',
  googleCalendar: 'Google Calendar',
  eventDatePlaceholder: 'YYYY-MM-DD HH:mm',
  openSource: 'Open source',
  sourceProduct: 'Mnelo · AGPL-3.0-only',
  sourceLicenseHeading: 'GNU Affero General Public License v3',
  sourceCopyright: 'Copyright © 2026 Mnelo contributors.',
  sourceNotice:
    'You may study, modify and redistribute Mnelo under AGPL version 3. The software is provided without warranty to the extent permitted by law. Third-party components retain their own licenses.',
  viewSource: 'View source code',
  thirdPartyNotices: 'Third-party licenses',
  showLicense: 'Read the full license',
  hideLicense: 'Close license text',
  you: 'You',
  quoteUnavailable: 'Original message is no longer on this device.',
  reactWith: 'React with {{emoji}}',
  moreReactions: 'More reactions',
  chooseEmoji: 'Choose an emoji',
  emojiKeyboard: 'Or use any emoji from your keyboard',
  addReaction: 'Add reaction',
  messageInfo: 'Message info',
  readBy: 'Read by',
  receiptRead: 'Read',
  receiptDelivered: 'Delivered',
  deliveredTo: 'Delivered to',
  deliveryPending: 'Not delivered yet',
  noReceiptsYet: 'No receipts yet',
  receiptHistoryUnavailable: 'Receipt history is unavailable for this message.',
  messageInfoUnavailable: 'This message is no longer available.',
  reactionCount_one: '{{emoji}}, {{count}} reaction',
  reactionCount_other: '{{emoji}}, {{count}} reactions',
  chatOptions: 'Chat options',
  callDirectionIncoming: 'Incoming',
  callDirectionOutgoing: 'Outgoing',
  callMissedVoice: 'Missed voice call',
  callMissedVideo: 'Missed video call',
  callBack: 'Call',
  callBackHint: 'Tap to call back',
  callOptionsHint: 'Opens call options',
  callStatusFailed: 'Failed',
  blockContact: 'Block contact',
  deliveryPeerNotReady:
    'A recipient is not ready for secure messaging yet. Ask them to update and open Mnelo. Pending messages stay on this device.',
  googleMaps: 'Google Maps',
  googleMapsShareHint: 'Choose a place in Google Maps, then tap Share → Mnelo to send it.',
  appleMaps: 'Apple Maps',
  openPhoto: 'Open photo',
  openVideo: 'Play video',
  videoUnavailable: 'Could not open this video.',
  saveSharePhoto: 'Save or share photo',
  messageRequests: 'Message requests',
  messageRequestHint:
    'Accept to connect and receive their messages. Their verified number is shown until they share a profile.',
  acceptRequest: 'Accept',
  blockRequest: 'Block',
  username: 'Username',
  usernamePlaceholder: '@username',
  addUsername: 'Set your username',
  usernameHint: '3–32 letters (a–z), numbers or underscores. You can set this later.',
  firstName: 'First name (optional)',
  lastName: 'Last name (optional)',
  localProfileHint:
    'Your profile is stored on this device, not in the phone directory. Sharing your contact code includes your display name. The username is not globally reserved or searchable; people find you by your verified number.',
  profileInvalid:
    'Check your username. First and last names together must be no longer than 60 characters.',
  searchChats: 'Search chats',
  filterAll: 'All',
  filterUnread: 'Unread',
  filterDirect: 'Direct',
  filterGroups: 'Groups',
  noChatResults: 'No chats match this search or filter.',
  unreadCount: '{{count}} unread messages',
  missedCount: '{{count}} missed calls',
  callMissed: 'Missed call',
  callDeclined: 'Call declined',
  callUnanswered: 'No answer',
  background_checking: 'Checking background notifications…',
  background_ready:
    'Background notifications are connected. Delivery depends on your device and network.',
  background_unavailable: 'Background notifications are temporarily unavailable. Try again.',
  'background_permission-required': 'Allow notifications to receive new-message alerts.',
  notifications: 'Notifications',
  notificationNewMessage: 'New message',
  morePhotos: '{{count}} more photos',
  notificationHint:
    'Choose whether names and message previews appear on the lock screen in your device settings.',
  notificationEnable: 'Enable device alerts',
  notificationSettings: 'Open notification settings',
  notificationEnabled: 'Notifications are on. You can turn them off in your device settings.',
  notificationDisabled: 'Device alerts are off. Unread counts still appear inside Mnelo.',
  notificationUnavailable: 'Device alerts are unavailable here.',
  notificationFailure:
    'An alert could not be shown. Check notification settings. Your local history is safe.',
  notificationOpen: 'Open',
  notificationDismiss: 'Dismiss notification',

  forward: 'Forward',
  read: 'Read on their device',
  groupDetails: 'Group details',
  saveGroup: 'Save group',
  leaveGroup: 'Leave group on this device',
  groupInfo: 'Group info',
  editGroup: 'Edit group',
  groupMembers: 'Members',
  groupMembersCount: 'Group · {{count}} members',
  groupAddDescription: 'Add group description',
  groupYou: 'You',
  groupAdmin: 'Admin',
  groupRemove: 'Remove',
  groupRemovePerson: 'Remove {{name}}',
  groupRemoveHint:
    'This person will no longer receive new group messages. Their existing history remains on their device.',
  groupLeaveHint:
    'New group messages will no longer arrive on this device. Your existing history stays here.',
  groupNoNewMembers: 'No more contacts to add.',
  deleteChat: 'Delete',
  exportDeleteChat: 'Export & delete',
  deleteChatHint:
    'Remove this chat and its history from this device? Other participants keep their copies. You remain a group member; new messages will bring the chat back.',
  exportDeleteHint:
    'Save a ZIP in Files, then delete this chat from this device. Cancelling the save keeps the chat. If new messages arrive, the chat is kept so nothing unsaved is lost.',
  exportMediaMissing:
    'Some attachments are unavailable. The chat was kept. You can export the available history from chat info.',
  groupAdminHint:
    'Only the group creator manages membership. Changes reach other devices when connected. Existing copies of history remain with each participant.',
  groupLeft: 'You are no longer sending or receiving in this group.',
  tagline: 'Your conversations. Your devices.',
  create: 'Create on this device',
  identityTitle: 'Make yourself known',
  identityHint:
    'Your name is stored locally and shared with the people you add. Manage phone registration and number discovery separately in Me.',
  deviceUnavailable:
    'Your private storage could not be opened. Update the development build or try again after unlocking your device.',
  localOnly: 'Device-owned messenger · development build',
  contacts: 'Contacts',
  addContact: 'Add a contact',
  contactName: 'Name on your device',
  contactCode: 'Their Mnelo code',
  myCode: 'My Mnelo code',
  copyCode: 'Copy my code',
  shareCode: 'Share my code',
  copied: 'Copied',
  contactHint:
    'Exchange codes through a channel you trust. Confirm the code with the person before adding them. Mnelo cannot replace a saved identity key.',
  confirmed: 'I confirmed this code with the person',
  noContacts: 'Add someone using their Mnelo code.',
  noChats: 'Your conversations will appear here.',
  newMessage: 'New message',
  newGroup: 'New group',
  groupAddMembers: 'Add members',
  groupNext: 'Next',
  groupMemberCount: '{{count}} / {{limit}} selected',
  groupSelectedMembers: 'Members ({{count}})',
  groupRemoveMember: 'Remove {{name}}',
  groupAdditionalInfo: 'Additional information',
  groupDescription: 'Group description',
  groupName: 'Group name',
  createGroup: 'Create group',
  groupHint: 'Choose up to 15 contacts. Every participant keeps their own history.',
  localHistory: 'History on this device',
  clearHistory: 'Clear history on this device',
  deleteLocal: 'Delete from this device',
  deleteEveryone: 'Delete for everyone',
  deletedMessage: 'This message was deleted',
  editMessage: 'Edit message',
  edited: 'Edited',
  deletionHint:
    'This removes only your local copy. Other participants keep their messages and files. Existing backups are separate copies.',
  confirmClear: 'Clear my local history',
  composer: 'Message…',
  pending: 'Waiting for the other device',
  delivered: 'Delivered to their device',
  received: 'Received on this device',
  peerOnline: 'Device connected',
  peerOffline: 'Waiting for a device connection',
  deliveryOffline: 'Waiting for internet. Your messages stay on this device until sent.',
  deliveryUpdate: 'This build cannot reach the messaging service. An update may be required.',
  deliveryIdentity: 'The contact’s security identity changed. Sending is paused.',
  deliverySomeFailed:
    'Some messages could not be processed. They will retry; other conversations can continue.',
  offlineHint: deliveryV2
    ? 'Once the service accepts an encrypted message, the recipient can receive it even if you go offline. Both people need internet for a live call.'
    : 'Unsent messages stay on your device. Delivery needs both devices to be reachable.',
  reply: 'Reply',
  copy: 'Copy text',
  retry: 'Retry delivery',
  photo: 'Photo',
  camera: 'Camera',
  file: 'File',
  voice: 'Voice message',
  location: 'Share location',
  contact: 'Share a contact',
  attachments: 'Add to message',
  showKeyboard: 'Show keyboard',
  openFile: 'Open file',
  openLocation: 'Open in Maps',
  mediaLimit: 'Choose a file up to 10 MB.',
  videoLimit: 'This video is over 10 MB. Trim it in Photos or choose a shorter video.',
  videoDurationLimit: 'Choose a video shorter than 1 hour.',
  mediaSelectionLimit: 'Choose up to 10 photos or videos at a time.',
  mediaPickerFailed:
    'Could not prepare this photo or video. Open it in Photos to download it, then try again.',
  mediaReadFailed: 'Could not read this file. Please select it again.',
  mediaBatchPartial:
    '{{sent}} of {{total}} items were saved to the chat. Select the remaining items to send them.',
  cameraPermission: 'Allow camera access in Settings to take a photo or video.',
  backups: 'Backup & recovery',
  backupRecoveryPending:
    'This development version can export your history, but restoring messaging access on another device is not yet supported. Keep the original installation. An export does not transfer your active encryption sessions.',
  backupOff: 'Automatic backup is off',
  backupHint:
    'You control your copies. Save an encrypted backup to your own iCloud Drive, Google Drive or another destination. Mnelo does not receive it.',
  exportBackup: 'Create encrypted backup',
  recoveryKey: 'Your recovery key',
  recoveryHint:
    'Keep this key separately from the backup. Without it, nobody at Mnelo can restore your history.',
  keySaved: 'I saved my recovery key separately',
  saveBackup: 'Choose where to save',
  backupShared:
    'The encrypted file was handed to your chosen app. Check that it was saved. Automatic cloud synchronization is not configured.',
  restore: 'Restore a backup',
  restoreHint:
    'Choose your encrypted backup and enter its recovery key. Restore requires a fresh device identity. Other people’s histories are not changed.',
  chooseBackup: 'Choose backup file',
  restoreNow: 'Restore on this device',
  restoreComplete: 'History restored. Previously unsent messages need an explicit retry.',
  backupResponsibility:
    'You are responsible for enabling, keeping and restoring your backups. Turning off backup does not delete existing copies.',
  settings: 'Settings',
  name: 'Display name',
  privacy: 'Privacy',
  privacyHint: deliveryV2
    ? 'Your history belongs on participant devices. Undelivered messages and files wait encrypted on Mnelo for up to 30 days and are removed after the receiving device acknowledges them or they expire. Content is decrypted on participant devices. Account and delivery-routing information are separate. Deleting your local copy leaves other participants’ copies unchanged.'
    : 'Your conversation history is held on participant devices. Local deletion never sends a request to delete another participant’s copy. Save or restore backups only when you choose.',
  block: 'Block on this device',
  unblock: 'Unblock',
  blocked: 'Blocked contacts',
  noBlocked: 'No blocked contacts.',
  genericError: 'This action could not be completed. Your existing local history has been kept.',
  callVoice: 'Voice call',
  newCall: 'New call',
  noCalls: 'No calls yet. Start a voice or video call with a saved contact.',
  noCallContacts: 'Add and verify a contact to start calling.',
  noCallResults: 'No saved contacts match this name.',
  callHistoryHint: 'Call history stays on this device.',
  callReturn: 'Return to current call',
  callChoose: 'Choose a contact',
  callOpenChat: 'Open conversation',
  callHistoryDelete: 'Remove from my history',
  callInformation: 'Call details for {{name}}',
  callHistoryDeleteHint:
    'This removes the call entry from Calls and its conversation on this device. The other person’s copy stays.',
  callVideo: 'Video call',
  callUnavailable: 'A verified device connection is needed to call.',
  callWaiting: 'Waiting for the other person…',
  callIncoming: 'Incoming call',
  callAccept: 'Accept',
  callDecline: 'Decline',
  callEnd: 'End call',
  callEnded: 'Call ended',
  callFailed: 'The call could not connect.',
  mute: 'Mute',
  unmute: 'Unmute',
  speaker: 'Speaker',
  earpiece: 'Earpiece',
  cameraOff: 'Camera off',
  cameraOn: 'Camera on',
  switchCamera: 'Switch camera',
  eraseDevice: 'Erase data on this device',
  eraseNumberToo: 'Also remove my number from registration and search',
  eraseHint:
    'This removes your local identity, contacts and history. Other people’s devices and existing backup files are unchanged. You can also unlink your number below; this requires the phone service to be reachable.',
  eraseConfirmed:
    'I understand that I will need my own backup and recovery key to restore this history',
} as const;
export const messengerKa: Record<keyof typeof messengerEn, string> = {
  callReply: 'შეტყობინებით პასუხი',
  callQuickReplies: 'ზარის სწრაფი პასუხები',
  callQuickRepliesHint:
    'აირჩიე პასუხი ზარის უარსაყოფად და შეტყობინების გასაგზავნად. ამ პასუხების შეცვლა შეგიძლია.',
  callQuickRepliesEditHint:
    'მოირგე პასუხები შენს სტილზე. ისინი მზად იქნება, როცა ზარზე პასუხს ვერ შეძლებ.',
  privacyMessages: 'პირადი მიმოწერა',
  settingsStorage: 'მონაცემები ამ მოწყობილობაზე',
  notificationDelivery: 'ახალი შეტყობინებების სიგნალი',
  notificationPreviews: 'სახელი და ტექსტის წინასწარი ნახვა',
  notificationOn: 'შეტყობინებები ჩართულია',
  notificationOff: 'შეტყობინებები გამორთულია',
  callQuickReplyLabel: 'პასუხი {{number}}',
  callReplyMeeting: 'შეხვედრაზე ვარ. მოგვიანებით გადმოგირეკავ.',
  callReplyLater: 'ახლა ვერ ვსაუბრობ. მოგვიანებით დაგირეკავ.',
  callReplySoon: 'რამდენიმე წუთში გადმოგირეკავ.',
  editReplies: 'პასუხების რედაქტირება',
  viewOriginal: 'თავდაპირველ შეტყობინებაზე გადასვლა',
  exportChat: 'ჩატის ექსპორტი',
  exportPreparing: 'ექსპორტი მზადდება…',
  exportLocalHint: 'შეინახე ამ მოწყობილობაზე არსებული მიმოწერისა და მედიის ასლი.',

  sendPoll: 'გამოკითხვის გაგზავნა',
  sendEvent: 'ღონისძიების გაგზავნა',
  pollHint: 'დასვი კითხვა და მიეცი მონაწილეებს ხმის მიცემის საშუალება.',
  eventHint: 'დაგეგმეთ ერთად და გაუზიარეთ დეტალები ამ ჩატს.',
  pollOptions: 'პასუხის ვარიანტები',
  pollPlaceholder: 'რისი კითხვა გსურს?',
  eventPlaceholder: 'ღონისძიების სახელწოდება',
  multipleAnswersHint: 'მონაწილეებს რამდენიმე პასუხის არჩევა შეუძლიათ.',
  eventLocationPlaceholder: 'ადგილი ან შეხვედრის ბმული',
  eventNotesPlaceholder: 'დამატებითი ინფორმაცია მონაწილეებისთვის',
  poll: 'გამოკითხვა',
  openChatSearch: 'ჩატებში ძებნის გახსნა',
  contactPhoneUnavailable: 'ამ კონტაქტის გასაზიარებელი ტელეფონის ნომერი არ არის ხელმისაწვდომი.',
  exportTooLarge: 'ეს ჩატი მეტისმეტად დიდია ერთ ZIP ფაილად გამოსატანად.',
  exportUnavailable: 'ამ მოწყობილობაზე ჩატის ექსპორტი მიუწვდომელია.',
  exportChanged: 'ექსპორტის დროს ჩატი შეიცვალა. გთხოვ, ხელახლა სცადო.',
  attachmentContact: 'კონტაქტი',
  attachmentLocation: 'ლოკაცია',
  attachmentMyLocation: 'ჩემი ლოკაცია',
  sendLocation: 'ლოკაციის გაგზავნა',
  locationSearch: 'ადგილის ან მისამართის ძებნა',
  locationMap: 'ადგილის არჩევა რუკაზე',
  locationHint: 'მოძებნე ადგილი ან რუკაზე ხანგრძლივი დაჭერით დასვი ნიშნული.',
  locationSelected: 'არჩეული ადგილი',
  locationSearching: 'იძებნება…',
  locationNoResults: 'ადგილი ვერ მოიძებნა. სცადე სხვა სიტყვა ან დასვი ნიშნული რუკაზე.',
  locationChoose: 'აირჩიე ადგილი შედეგებიდან.',
  locationCoordinatesHint:
    'შეიყვანე გასაზიარებელი ადგილის კოორდინატები. გაგზავნამდე შეგიძლია რუკაზე ნახო.',
  latitude: 'განედი',
  longitude: 'გრძედი',
  event: 'ივენთი',
  createPoll: 'გამოკითხვის შექმნა',
  createEvent: 'ივენთის შექმნა',
  pollQuestion: 'კითხვა',
  pollOption: 'ვარიანტი {{number}}',
  removeOption: 'ვარიანტი {{number}} — წაშლა',
  addOption: 'ვარიანტის დამატება',
  multipleAnswers: 'რამდენიმე პასუხის არჩევა',
  chooseMany: 'აირჩიე ერთი ან რამდენიმე პასუხი',
  chooseOne: 'აირჩიე ერთი პასუხი',
  pollChoice: '{{option}}: {{count}} ხმა',
  pollVoters_one: 'ხმა მისცა {{count}} მონაწილემ',
  pollVoters_other: 'ხმა მისცა {{count}} მონაწილემ',
  eventTitle: 'ივენთის სახელი',
  eventStart: 'დაწყება',
  eventEnd: 'დასრულება',
  eventLocation: 'ადგილი (არასავალდებულო)',
  eventNotes: 'აღწერა (არასავალდებულო)',
  eventCalendarHint: 'ჩატის მონაწილეებს შეუძლიათ ივენთი თავიანთ კალენდარში დაამატონ.',
  addToCalendar: 'კალენდარში დამატება',
  phoneCalendar: 'ტელეფონის კალენდარი',
  googleCalendar: 'Google Calendar',
  eventDatePlaceholder: 'YYYY-MM-DD HH:mm',
  openSource: 'ღია კოდი',
  sourceProduct: 'Mnelo · ლიცენზია AGPL-3.0-only',
  sourceLicenseHeading: 'GNU Affero General Public License — ვერსია 3',
  sourceCopyright: 'საავტორო უფლება © 2026 Mnelo-ს კონტრიბუტორები.',
  sourceNotice:
    'Mnelo-ს შესწავლა, შეცვლა და გავრცელება შეგიძლიათ AGPL-ის მე-3 ვერსიის პირობებით. პროგრამა მოწოდებულია გარანტიის გარეშე, კანონით დაშვებულ ფარგლებში. მესამე მხარის კომპონენტები საკუთარ ლიცენზიებს ინარჩუნებს.',
  viewSource: 'საწყისი კოდის ნახვა',
  thirdPartyNotices: 'მესამე მხარის ლიცენზიები',
  showLicense: 'სრული ლიცენზიის წაკითხვა',
  hideLicense: 'ლიცენზიის ტექსტის დახურვა',
  you: 'შენ',
  quoteUnavailable: 'საწყისი შეტყობინება ამ მოწყობილობაზე აღარ არის.',
  reactWith: 'რეაქცია {{emoji}}',
  moreReactions: 'სხვა რეაქციები',
  chooseEmoji: 'აირჩიე ემოჯი',
  emojiKeyboard: 'ან აირჩიე ნებისმიერი ემოჯი კლავიატურიდან',
  addReaction: 'რეაქციის დამატება',
  messageInfo: 'შეტყობინების ინფორმაცია',
  readBy: 'წაიკითხა',
  receiptRead: 'წაკითხულია',
  receiptDelivered: 'მიწოდებულია',
  deliveredTo: 'მიუვიდა',
  deliveryPending: 'ჯერ არ ჩაბარებულა',
  noReceiptsYet: 'ჯერ არ არის დადასტურებული',
  receiptHistoryUnavailable:
    'ამ შეტყობინების ჩაბარებისა და წაკითხვის ისტორია არ არის ხელმისაწვდომი.',
  messageInfoUnavailable: 'ეს შეტყობინება აღარ არის ხელმისაწვდომი.',
  reactionCount_one: '{{emoji}}, {{count}} რეაქცია',
  reactionCount_other: '{{emoji}}, {{count}} რეაქცია',
  chatOptions: 'ჩატის პარამეტრები',
  callDirectionIncoming: 'შემოსული',
  callDirectionOutgoing: 'გასული',
  callMissedVoice: 'გამოტოვებული ხმოვანი ზარი',
  callMissedVideo: 'გამოტოვებული ვიდეოზარი',
  callBack: 'დარეკვა',
  callBackHint: 'შეეხე გადასარეკად',
  callOptionsHint: 'ზარის მენიუს გახსნა',
  callStatusFailed: 'ვერ შედგა',
  blockContact: 'კონტაქტის დაბლოკვა',
  deliveryPeerNotReady:
    'ერთ-ერთი მიმღები დაცული მიმოწერისთვის ჯერ მზად არ არის. სთხოვეთ, განაახლოს და გახსნას Mnelo. გასაგზავნი შეტყობინებები ამ მოწყობილობაზე რჩება.',
  googleMaps: 'Google Maps',
  googleMapsShareHint: 'Google Maps-ში აირჩიე ადგილი, შემდეგ Share → Mnelo-თი გააზიარე.',
  appleMaps: 'Apple Maps',
  openPhoto: 'ფოტოს გახსნა',
  openVideo: 'ვიდეოს დაკვრა',
  videoUnavailable: 'ვიდეოს გახსნა ვერ მოხერხდა.',
  saveSharePhoto: 'ფოტოს შენახვა ან გაზიარება',
  messageRequests: 'მიმოწერის მოთხოვნები',
  messageRequestHint:
    'მიმოწერის დასაწყებად მიიღე მოთხოვნა. პროფილის გაზიარებამდე დადასტურებული ნომერი გამოჩნდება.',
  acceptRequest: 'მიღება',
  blockRequest: 'დაბლოკვა',
  username: 'იუზერნეიმი',
  usernamePlaceholder: '@saxeli',
  addUsername: 'იუზერნეიმის მითითება',
  usernameHint: '3–32 ლათინური ასო (a–z), ციფრი ან ქვედა ტირე. მითითება მოგვიანებითაც შეგიძლია.',
  firstName: 'სახელი (არასავალდებულო)',
  lastName: 'გვარი (არასავალდებულო)',
  localProfileHint:
    'პროფილი ინახება ამ მოწყობილობაზე და არა ნომრების საძიებელში. კონტაქტის კოდის გაზიარება საჩვენებელ სახელსაც აზიარებს. იუზერნეიმი გლობალურად არ იჯავშნება და არ იძებნება; სხვები დადასტურებული ნომრით გპოულობენ.',
  profileInvalid: 'გადაამოწმე იუზერნეიმი. სახელი და გვარი ერთად 60 სიმბოლოზე გრძელი არ უნდა იყოს.',
  searchChats: 'ჩატების ძებნა',
  filterAll: 'ყველა',
  filterUnread: 'წაუკითხავი',
  filterDirect: 'პირადი',
  filterGroups: 'ჯგუფები',
  noChatResults: 'ამ ძებნით ან ფილტრით ჩატები ვერ მოიძებნა.',
  unreadCount: '{{count}} წაუკითხავი შეტყობინება',
  missedCount: '{{count}} გამოტოვებული ზარი',
  callMissed: 'გამოტოვებული ზარი',
  callDeclined: 'უარყოფილი ზარი',
  callUnanswered: 'უპასუხო ზარი',
  background_checking: 'ფონური შეტყობინებების კავშირი მოწმდება…',
  background_ready:
    'ფონური შეტყობინებები დაკავშირებულია. მიღება დამოკიდებულია მოწყობილობასა და ქსელზე.',
  background_unavailable: 'ფონური შეტყობინებები დროებით მიუწვდომელია. სცადეთ ხელახლა.',
  'background_permission-required':
    'ახალი შეტყობინებების სიგნალისთვის ჩართეთ შეტყობინებების ნებართვა.',
  notifications: 'შეტყობინებები',
  notificationNewMessage: 'ახალი შეტყობინება',
  morePhotos: 'კიდევ {{count}} ფოტო',
  notificationHint:
    'მოწყობილობის პარამეტრებში აირჩიე, გამოჩნდეს თუ არა სახელი და შეტყობინების ტექსტი ჩაკეტილ ეკრანზე.',
  notificationEnable: 'მოწყობილობის შეტყობინებების ჩართვა',
  notificationSettings: 'შეტყობინებების პარამეტრების გახსნა',
  notificationEnabled:
    'შეტყობინებები ჩართულია. მათი გამორთვა მოწყობილობის პარამეტრებიდან შეგიძლია.',
  notificationDisabled:
    'მოწყობილობის შეტყობინებები გამორთულია. წაუკითხავების რაოდენობა Mnelo-ში მაინც გამოჩნდება.',
  notificationUnavailable: 'მოწყობილობის შეტყობინებები აქ მიუწვდომელია.',
  notificationFailure:
    'შეტყობინება ვერ გამოჩნდა. გადაამოწმე შეტყობინებების პარამეტრები. ადგილობრივი ისტორია შენახულია.',
  notificationOpen: 'გახსნა',
  notificationDismiss: 'შეტყობინების დახურვა',

  forward: 'გადაგზავნა',
  read: 'წაკითხულია მის მოწყობილობაზე',
  groupDetails: 'ჯგუფის დეტალები',
  saveGroup: 'ჯგუფის შენახვა',
  leaveGroup: 'ჯგუფიდან გასვლა ამ მოწყობილობაზე',
  groupInfo: 'ჯგუფის ინფორმაცია',
  editGroup: 'ჯგუფის რედაქტირება',
  groupMembers: 'წევრები',
  groupMembersCount: 'ჯგუფი · {{count}} წევრი',
  groupAddDescription: 'ჯგუფის აღწერის დამატება',
  groupYou: 'შენ',
  groupAdmin: 'ადმინი',
  groupRemove: 'წაშლა',
  groupRemovePerson: '{{name}} — ჯგუფიდან წაშლა',
  groupRemoveHint:
    'ეს წევრი ჯგუფის ახალ შეტყობინებებს ვეღარ მიიღებს. ძველი ისტორია მის მოწყობილობაზე დარჩება.',
  groupLeaveHint: 'ამ მოწყობილობაზე ჯგუფის ახალი შეტყობინებები აღარ მოვა. ძველი ისტორია დარჩება.',
  groupNoNewMembers: 'დასამატებელი კონტაქტები არ არის.',
  deleteChat: 'წაშლა',
  exportDeleteChat: 'ექსპორტი და წაშლა',
  deleteChatHint:
    'წაიშალოს ჩატი და მისი ისტორია ამ მოწყობილობიდან? სხვა მონაწილეების ასლები დარჩება. ჯგუფის წევრად რჩები; ახალი შეტყობინებისას ჩატი კვლავ გამოჩნდება.',
  exportDeleteHint:
    'შეინახე ZIP ფაილებში, შემდეგ ჩატი ამ მოწყობილობიდან წაიშლება. შენახვის გაუქმებისას ჩატი დარჩება. თუ ახალი შეტყობინება მოვა, ჩატი შენარჩუნდება, რათა შეუნახავი მიმოწერა არ დაიკარგოს.',
  exportMediaMissing:
    'ზოგი დანართი მიუწვდომელია. ჩატი შენარჩუნებულია. ხელმისაწვდომი ისტორიის ექსპორტი ჩატის ინფორმაციიდან შეგიძლია.',
  groupAdminHint:
    'მონაწილეებს მხოლოდ ჯგუფის შემქმნელი მართავს. ცვლილებები სხვა მოწყობილობებზე კავშირისას მიდის. ისტორიის არსებული ასლები მონაწილეებთან რჩება.',
  groupLeft: 'ამ ჯგუფში აღარ აგზავნი და იღებ შეტყობინებებს.',
  eraseDevice: 'მონაცემების წაშლა ამ მოწყობილობიდან',
  eraseNumberToo: 'ჩემი ნომერიც წაიშალოს რეგისტრაციიდან და ძებნიდან',
  eraseHint:
    'წაიშლება ამ მოწყობილობის ვინაობა, კონტაქტები და ისტორია. სხვისი მოწყობილობები და არსებული სარეზერვო ფაილები უცვლელი რჩება. ქვემოთ ნომრის კავშირის გაუქმებაც შეგიძლია; ამისთვის ნომრის სერვისი ხელმისაწვდომი უნდა იყოს.',
  eraseConfirmed:
    'მესმის, რომ ამ ისტორიის აღსადგენად საკუთარი ასლი და აღდგენის გასაღები დამჭირდება',
  tagline: 'შენი საუბრები. შენი მოწყობილობები.',
  create: 'შექმენი ამ მოწყობილობაზე',
  identityTitle: 'გაგვეცანი',
  identityHint:
    'შენი სახელი ინახება შენს მოწყობილობაზე და ზიარდება შენს მიერ დამატებულ ადამიანებთან. ნომრის რეგისტრაცია და ნომრით პოვნა იმართება განყოფილებიდან „მე“.',
  deviceUnavailable:
    'პირადი საცავი ვერ გაიხსნა. განაახლე განვითარების ვერსია ან სცადე მოწყობილობის განბლოკვის შემდეგ.',
  localOnly: 'მონაცემები მოწყობილობაზე · სატესტო ვერსია',
  contacts: 'კონტაქტები',
  addContact: 'კონტაქტის დამატება',
  contactName: 'სახელი შენს მოწყობილობაზე',
  contactCode: 'მისი Mnelo კოდი',
  myCode: 'ჩემი Mnelo კოდი',
  copyCode: 'ჩემი კოდის კოპირება',
  shareCode: 'ჩემი კოდის გაზიარება',
  copied: 'დაკოპირებულია',
  contactHint:
    'გაცვალეთ კოდები სანდო გზით. დამატებამდე გადაამოწმე კოდი ამ ადამიანთან. Mnelo ვერ ჩაანაცვლებს შენახულ საიდენტიფიკაციო გასაღებს.',
  confirmed: 'ამ ადამიანთან კოდი გადავამოწმე',
  noContacts: 'დაამატე ადამიანი მისი Mnelo კოდით.',
  noChats: 'შენი მიმოწერები აქ გამოჩნდება.',
  newMessage: 'ახალი მიმოწერა',
  newGroup: 'ახალი ჯგუფი',
  groupAddMembers: 'წევრების დამატება',
  groupNext: 'შემდეგი',
  groupMemberCount: 'მონიშნულია {{count}} / {{limit}}',
  groupSelectedMembers: 'წევრები ({{count}})',
  groupRemoveMember: '{{name}} — მონიშვნის გაუქმება',
  groupAdditionalInfo: 'დამატებითი ინფორმაცია',
  groupDescription: 'ჯგუფის აღწერა',
  groupName: 'ჯგუფის სახელი',
  createGroup: 'ჯგუფის შექმნა',
  groupHint: 'აირჩიე მაქსიმუმ 15 კონტაქტი. თითოეული მონაწილე ინახავს საკუთარ ისტორიას.',
  localHistory: 'ისტორია ამ მოწყობილობაზე',
  clearHistory: 'ისტორიის წაშლა ამ მოწყობილობიდან',
  deleteLocal: 'ამ მოწყობილობიდან წაშლა',
  deleteEveryone: 'ყველასთან წაშლა',
  deletedMessage: 'შეტყობინება წაშლილია',
  editMessage: 'შეტყობინების რედაქტირება',
  edited: 'რედაქტირებულია',
  deletionHint:
    'იშლება მხოლოდ შენი ადგილობრივი ასლი. სხვა მონაწილეებს რჩებათ მიმოწერა და ფაილები. სარეზერვო ასლები დამოუკიდებლად ინახება.',
  confirmClear: 'ჩემი ადგილობრივი ისტორიის წაშლა',
  composer: 'შეტყობინება…',
  pending: 'ველოდებით მეორე მოწყობილობას',
  delivered: 'მიწოდებულია მის მოწყობილობაზე',
  received: 'მიღებულია ამ მოწყობილობაზე',
  peerOnline: 'მოწყობილობა დაკავშირებულია',
  peerOffline: 'ველოდებით მოწყობილობასთან კავშირს',
  deliveryOffline: 'ველოდებით ინტერნეტს. გაგზავნამდე შეტყობინებები ამ მოწყობილობაზე რჩება.',
  deliveryUpdate: 'ეს ვერსია მიმოწერის სერვისს ვერ უკავშირდება. შესაძლოა განახლება იყოს საჭირო.',
  deliveryIdentity: 'კონტაქტის უსაფრთხოების იდენტობა შეიცვალა. გაგზავნა შეჩერებულია.',
  deliverySomeFailed: 'ზოგი შეტყობინება ვერ დამუშავდა. ხელახლა ვცდით; სხვა მიმოწერები გრძელდება.',
  offlineHint: deliveryV2
    ? 'როცა სერვისი დაშიფრულ შეტყობინებას მიიღებს, ადრესატს მისი მიღება შენი ინტერნეტიდან გასვლის შემდეგაც შეუძლია. ცოცხალი ზარისთვის ინტერნეტი ორივე მხარეს სჭირდება.'
    : 'გაუგზავნელი შეტყობინებები რჩება შენს მოწყობილობაზე. მისაწოდებლად ორივე მოწყობილობა ხელმისაწვდომი უნდა იყოს.',
  reply: 'პასუხი',
  copy: 'ტექსტის კოპირება',
  retry: 'მიწოდების ხელახლა ცდა',
  photo: 'ფოტო',
  camera: 'კამერა',
  file: 'ფაილი',
  voice: 'ხმოვანი შეტყობინება',
  location: 'მდებარეობის გაზიარება',
  contact: 'კონტაქტის გაზიარება',
  attachments: 'შეტყობინებაზე დამატება',
  showKeyboard: 'კლავიატურის გახსნა',
  openFile: 'ფაილის გახსნა',
  openLocation: 'რუკაში გახსნა',
  mediaLimit: 'აირჩიე მაქსიმუმ 10 მბ ზომის ფაილი.',
  videoLimit: 'ვიდეო 10 მბ-ზე დიდია. შეამოკლე Photos-ში ან აირჩიე უფრო მოკლე ვიდეო.',
  videoDurationLimit: 'აირჩიე 1 საათზე მოკლე ვიდეო.',
  mediaSelectionLimit: 'ერთდროულად აირჩიე მაქსიმუმ 10 ფოტო ან ვიდეო.',
  mediaPickerFailed:
    'ფოტო ან ვიდეო ვერ მომზადდა. გახსენი Photos-ში ჩამოსატვირთად და სცადე ხელახლა.',
  mediaReadFailed: 'ფაილი ვერ წავიკითხეთ. აირჩიე ხელახლა.',
  mediaBatchPartial:
    'ჩატში შეინახა {{sent}} ფაილი {{total}}-დან. გასაგზავნად აირჩიე დარჩენილი ფაილები.',
  cameraPermission: 'ფოტოს ან ვიდეოს გადასაღებად Settings-ში დაუშვი კამერის წვდომა.',
  backups: 'სარეზერვო ასლი და აღდგენა',
  backupRecoveryPending:
    'ამ სატესტო ვერსიას ისტორიის ასლის შენახვა შეუძლია, მაგრამ სხვა მოწყობილობაზე მიმოწერის წვდომის აღდგენა ჯერ მზად არ არის. შეინარჩუნე საწყისი აპი. ასლი დაშიფვრის მოქმედ სესიებს არ გადაიტანს.',
  backupOff: 'ავტომატური ასლი გამორთულია',
  backupHint:
    'ასლებს თავად მართავ. შეინახე დაშიფრული ასლი შენს iCloud Drive-ში, Google Drive-ში ან სხვა საცავში. Mnelo მას არ იღებს.',
  exportBackup: 'დაშიფრული ასლის შექმნა',
  recoveryKey: 'შენი აღდგენის გასაღები',
  recoveryHint:
    'გასაღები ასლისგან განცალკევებით შეინახე. მის გარეშე Mnelo შენს ისტორიას ვერ აღადგენს.',
  keySaved: 'აღდგენის გასაღები ცალკე შევინახე',
  saveBackup: 'შენახვის ადგილის არჩევა',
  backupShared:
    'დაშიფრული ფაილი გადაეცა შენს მიერ არჩეულ აპს. გადაამოწმე, რომ შენახულია. ღრუბელთან ავტომატური სინქრონიზაცია გამართული არ არის.',
  restore: 'სარეზერვო ასლის აღდგენა',
  restoreHint:
    'აირჩიე დაშიფრული ასლი და ჩაწერე აღდგენის გასაღები. აღდგენა შესაძლებელია ახალ მოწყობილობაზე, ვინაობის შექმნამდე. სხვისი ისტორია არ იცვლება.',
  chooseBackup: 'ასლის ფაილის არჩევა',
  restoreNow: 'ამ მოწყობილობაზე აღდგენა',
  restoreComplete: 'ისტორია აღდგენილია. ადრე გაუგზავნელ შეტყობინებებს ხელახლა ცდა სჭირდება.',
  backupResponsibility:
    'ასლების ჩართვას, შენახვასა და აღდგენას თავად მართავ. ასლის გამორთვა უკვე შენახულ ასლებს არ შლის.',
  settings: 'პარამეტრები',
  name: 'საჩვენებელი სახელი',
  privacy: 'კონფიდენციალურობა',
  privacyHint: deliveryV2
    ? 'ისტორია მონაწილეების მოწყობილობებზეა. მიუწოდებელი შეტყობინებები და ფაილები Mnelo-ზე დაშიფრულად ელოდება მაქსიმუმ 30 დღე და იშლება მიმღების მოწყობილობის დასტურის ან ვადის გასვლის შემდეგ. შიგთავსი მონაწილეების მოწყობილობებზე იშიფრება. ანგარიშისა და მიწოდების ტექნიკური მონაცემები ცალკეა. შენი ასლის წაშლა სხვის ასლს არ შლის.'
    : 'მიმოწერის ისტორია ინახება მონაწილეების მოწყობილობებზე. ადგილობრივი წაშლა მეორე მონაწილის ასლის წაშლის მოთხოვნას არ აგზავნის. სარეზერვო ასლი მხოლოდ შენი არჩევანით შეინახე ან აღადგინე.',
  block: 'ამ მოწყობილობაზე დაბლოკვა',
  unblock: 'განბლოკვა',
  blocked: 'დაბლოკილი კონტაქტები',
  noBlocked: 'დაბლოკილი კონტაქტები არ არის.',
  genericError: 'მოქმედება ვერ დასრულდა. არსებული ადგილობრივი ისტორია შენარჩუნებულია.',
  callVoice: 'ხმოვანი ზარი',
  newCall: 'ახალი ზარი',
  noCalls: 'ზარები ჯერ არ არის. დაურეკე შენახულ კონტაქტს ხმით ან ვიდეოთი.',
  noCallContacts: 'დასარეკად დაამატე და გადაამოწმე კონტაქტი.',
  noCallResults: 'ამ სახელით შენახული კონტაქტი ვერ მოიძებნა.',
  callHistoryHint: 'ზარების ისტორია ამ მოწყობილობაზე რჩება.',
  callReturn: 'მიმდინარე ზარზე დაბრუნება',
  callChoose: 'აირჩიე კონტაქტი',
  callOpenChat: 'მიმოწერის გახსნა',
  callHistoryDelete: 'ჩემი ისტორიიდან წაშლა',
  callInformation: '{{name}} — ზარის ინფორმაცია',
  callHistoryDeleteHint:
    'ზარის ჩანაწერი წაიშლება ამ მოწყობილობის ზარებიდან და შესაბამისი ჩატიდან. მეორე ადამიანის ასლი დარჩება.',
  callVideo: 'ვიდეოზარი',
  callUnavailable: 'დასარეკად საჭიროა გადამოწმებულ მოწყობილობასთან კავშირი.',
  callWaiting: 'ველოდებით მეორე ადამიანს…',
  callIncoming: 'შემომავალი ზარი',
  callAccept: 'მიღება',
  callDecline: 'უარყოფა',
  callEnd: 'ზარის დასრულება',
  callEnded: 'ზარი დასრულდა',
  callFailed: 'ზარი ვერ შედგა.',
  mute: 'მიკროფონის გამორთვა',
  unmute: 'მიკროფონის ჩართვა',
  speaker: 'დინამიკი',
  earpiece: 'ყურსასმენი',
  cameraOff: 'კამერის გამორთვა',
  cameraOn: 'კამერის ჩართვა',
  switchCamera: 'კამერის შეცვლა',
};
